name: base build
description: 'Building time!'
inputs:
  project:
    description: 'Project name'
    required: true
  registryPassword:
    required: true
    description: 'Password to docker registry'

runs:
  using: "composite"
  steps:
     # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v1

    # Login against a target registry
    - name: Login to Dockerhub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: altervisionhub
        password: ${{ inputs.registryPassword }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: docker.io/altervisionhub/${{ inputs.project }}

    - name: Build dependencies
      id: docker-build-deps
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        target: deps
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test
      id: docker-test
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        target: deps
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build
      id: docker-build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        target: deps
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build runtime
      id: docker-build-runtime
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        target: deps
        cache-from: type=gha
        cache-to: type=gha,mode=max
