name: Build and push docker image

on:
  workflow_call:
    inputs:
      project:
        description: 'Project name'
        required: true
        type: string


jobs:
  Docker:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      # Login against a target registry
      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: altervisionhub
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: docker.io/altervisionhub/${{ inputs.project }}

      - name: Build dependencies
        id: docker-build-deps
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: deps
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test
        id: docker-test
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: build
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build runtime
        id: docker-build-runtime
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: runtime
          cache-from: type=gha
          cache-to: type=gha,mode=max
