name: Build and push docker image

on:
  workflow_call:
    inputs:
      project:
        description: 'Project name'
        required: true
        type: string
    secrets:
      registryPassword:
        required: true

jobs:
  prepare:
    name: Prepare the environment
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      # Login against a target registry
      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: altervisionhub
          password: ${{ secrets.registryPassword }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: docker.io/altervisionhub/${{ inputs.project }}
  deps:
    name: Download dependencies
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Build dependencies
        id: docker-build-deps
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: deps
          cache-from: type=gha
          cache-to: type=gha,mode=max
  test:
    name: Execute tests
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - name: Test
        id: docker-test
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build:
    name: Build executable
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - name: Build
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: build
          cache-from: type=gha
          cache-to: type=gha,mode=max
  push:
    name: Build and push runtime image
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Build runtime
        id: docker-build-runtime
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: runtime
          cache-from: type=gha
          cache-to: type=gha,mode=max
